# Generated by Django 2.1.5 on 2019-04-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
